# Site wide configuration

title: 一起踢·足球训练营
description: "致力于提高足球技术的平台"
logo: 120x120.gif
teaser: start.jpg
locale: en_CN
url: //zuqiuxunlian.com

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: 王腾
  web: http://zuqiuxunlian.com
  email: awong1900@163.com
  twitter: awong1900
  bio: ""
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +Ten Wong
    ad-client: ca-pub-6914305251560584
    ad-slot: 9353650158

analytics:
    baidu: 2a36203f824f2dff471775364d62fc7d

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
